#!/usr/bin/env bash
#
# Summary: Exec an action over all element passed via param
#
# Usage: pm _exec-action-over-all "basher:npm:brew" <command>

set -e

action=$2
elements=$1

if [ -z "$elements" ]; then
    pm-help _exec-action-over-all
    exit 1
fi

IFS=:

for pmname in $elements;
do
    echo "${pmname}"
    pm-${pmname} ${action}
done

