#!/usr/bin/env bash
#
# Summary: Display all installed packages
#
# Usage: pm list

set -e

pms=(
npm
basher
)

for pmname in ${pms[*]};
do
    echo "${pmname}"
    pm-${pmname} list
done

echo "** Brew **"
brew list
echo "** Brew Cask **"
brew cask list
echo "** Pip **"
pip list
