#!/usr/bin/env bash

echo "" \
&& echo "** Global npm **" \
&& echo "" \
&& ls /usr/local/lib/node_modules/ \
&& echo "" \
&& echo "** Basher **" \
&& echo "" \
&& basher list \
&& echo "" \
&& echo "** Brew **" \
&& echo "" \
&& brew list \
&& echo "" \
&& echo "** Brew Cask **" \
&& echo "" \
&& brew cask list \
&& echo "" \
&& echo "** Pip **" \
&& echo "" \
&& pip list
