#!/usr/bin/env bash


echo "** Global npm **"
ls /usr/local/lib/node_modules/
npm -g list --depth=0
echo "** Basher **"
basher list
echo "** Brew **"
brew list
echo "** Brew Cask **"
brew cask list
echo "** Pip **"
pip list
