#!/usr/bin/env bash
#
# Summary: Show out of date installed packages
#
# Usage: pm outdated
#

set -e

pms=(
npm
basher
)

for pmname in ${pms[*]};
do
    echo "${pmname}"
    pm-${pmname} outdated
done

echo "brew" ;
brew outdated ;
echo "brew cask" ;
brew cask outdated ;
echo "pip" ;
pip list --outdated ;
