#!/usr/bin/env bash
#
# Summary: Show out of date installed packages
#
# Usage: pm outdated
#

echo "npm";
npm -g outdated ;
echo "basher" ;
basher outdated ;
echo "brew" ;
brew outdated ;
echo "brew cask" ;
brew cask outdated ;
echo "pip" ;
pip list --outdated ;
