#!/usr/bin/env bash
#
# Summary:
#    Update all outdated packages
#
#    brew cask reinstall unity web-player as sudo all time
#    npm has not update only global outdated packages
#
# Usage: pm update
#
npm install -g npm 
npm update -g
basher update
for p in $(basher outdated); do echo "Update "$p" ..."; basher upgrade $p; done
brew update
brew upgrade
composer self-update
pip3 install --upgrade pip
pip_upgrade_outdated
brew cask upgrade
for p in $(brew cask list); do echo "Update "$p" ..."; brew cask upgrade $p; done
