#!/usr/bin/env bash

npm install -g npm yarn yo ava backstopjs gulp-cli typescript tslint  @angular/cli react-static bower
basher update
for p in $(basher outdated); do echo "Update "$p" ..."; basher upgrade $p; done
brew update
brew upgrade
composer self-update
pip3 install --upgrade pip
pip_upgrade_outdated
brew cask upgrade
for p in $(brew cask list); do echo "Update "$p" ..."; brew cask upgrade $p; done
